name: Waka Readme

on:
  schedule:
    # Runs at 0600 UTC
    - cron: '00 06 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: miermontoto/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: TRUE
          SHOW_LANGUAGE: FALSE
          SHOW_TIMEZONE: FALSE
          SHOW_EDITORS: FALSE
          SHOW_LANGUAGE_PER_REPO: FALSE
